<!DOCTYPE html>
<html lang="en" ng-app="help">
<head>
	<meta charset="utf-8">
	<title><?= $page->title ?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="<?= $page->description ?>">
	<meta name="author" content="<?= $page->author ?>"/>
	<link rel="me" type="text/html" href="https://plus.google.com/102792250956539127203"/>
	<meta name="generator" content="Sphido CMS"/>
	<link rel="shortcut icon" href="<?= url('favicon.ico') ?>" type="image/x-icon"/>
	<link rel="stylesheet" href="<?= url('css/style.css') ?>" type="text/css"/>
</head>

<body class="<?= $page->class ?>" onload="prettyPrint()">

<div class="container">
	<h1>Here is how to use PHTML</h1>
	<!-- nice trick how to embed source code -->
	<p>Here is an source code: <code><?= $page->getSlug() ?>/index.phtml</code></p>
	<pre class="prettyprint"><code><?= htmlspecialchars($page->getContent()) ?></code></pre>
</div>

<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"/>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/prettify/r224/prettify.js"></script>

</body>
</html>