# Create 3 dimesional array
import numpy as np
a = np.array([(0,1,2),(3,4,5),(6,7,8)])
print(a[0][2])
print(a[0,2])
print(a[:2])
print()
print(a[:3,:2])
print()
print(a[2,:3])
print()
print(a[:3,2])
print()
print(a[:2,1])
print()
print(a[1:,1])
print()
print(a[:2,:1])
print()
print(a[2:,:])
print()
print(a[:,:2])
print()
print(a[1,:2])
print()
print(a[1:2,:2])
print()

array = np.arange(8)
print("Original array : \n", array)
array = np.arange(8).reshape(4,2)
print("After reshape : \n", array)
array = np.arange(8).reshape(2,2,2)
print("After reshape : \n", array)
print(array.ndim)
print()
print(array[array>4])
print()
arr = np.array(['Alpha', 'Beta', 'Gamma', 'Alpha', 'Omega', 'Pi', 'Beta', 'Alpha', 'Delta'])
print(arr[arr=='Alpha'])
print()

data = np.random.randn(9,4)
print(data)

print(data[arr=='Alpha', 2:])
print(data[arr=='Alpha', 1:])
print(data[arr=='Alpha', 0:])
print(data[~(arr=='Alpha')])
print()
c = arr == 'Beta'
print(data[c])
print()
print(data[~c])
print()
print(data[arr!='Alpha'])
print()
c = (arr=='Alpha') | (arr=='Gama')
print(data[c])
print(type(c))

print(data[data > 0])
print(data[data < 0])
data[data < 0] = 1
print(data)
print()

print(a.T)
print(a.transpose(1,0))

arr = np.arange(16).reshape((2,2,4))
print(arr)
print()
print(arr.transpose(1,0,2))
print()
print(arr.transpose(2,0,1))
print()
print(arr.transpose(2,1,0))
print()
print(arr.transpose(0,1,2))
print()
print(arr.T)

arr1 = np.arange(4)
arr2 = np.random.randn(4)
print(np.dot(arr1, arr2))

# arr1 = np.arr1(2,2)
# arr2 = np.arr2(3,3)
# print(np.dot(arr1, arr2))

print(np.sqrt(a))
print(np.sqrt(arr))
print(np.sqrt(arr1))