<?php
echo("floor<br />");
echo(floor(0.60) . "<br />");
echo(floor(0.40) . "<br />");
echo(floor(5) . "<br />");
echo(floor(5.1) . "<br />");
echo(floor(-5.1) . "<br />");
echo(floor(-5.9));
echo("<br />ceil");
echo("<br />");
echo(ceil(0.60) . "<br />");
echo(ceil(0.40) . "<br />");
echo(ceil(5) . "<br />");
echo(ceil(5.1) . "<br />");
echo(ceil(-5.1) . "<br />");
echo(ceil(-5.9));
echo("<br />round");
echo("<br />");
echo(round(0.60) . "<br />");
echo(round(0.40) . "<br />");
echo(round(0.50) . "<br />");
echo(round(5) . "<br />");
echo(round(5.1) . "<br />");
echo(round(-5.1) . "<br />");
echo(round(-5.9));
echo("<br />abs");
echo("<br />");
echo(abs(0.60) . "<br />");
echo(abs(0.40) . "<br />");
echo(abs(5) . "<br />");
echo(abs(5.1) . "<br />");
echo(abs(-5.1) . "<br />");
echo(abs(-5.9));
?>